#!/bin/sh 
":" //# comment; exec /usr/bin/env node --harmony_proxies "$0" "$@"

'use strict'
/*
|--------------------------------------------------------------------------
|   Running Console Commands
|--------------------------------------------------------------------------
|
|  Here we invoke console commands registered under Ace store.
|
*/
const kernel = require('./bootstrap/kernel')
kernel()
