# use plural word to define entity
# box is sample field
# for read validation rules see at http://indicative.adonisjs.com/
box:
  integer_field: integer
  string_field: string
  text_field: text
  float_field: float,5,2
  decimal_field: decimal,5,2
  boolean_field: boolean
  date_field: date
  datetime_field: datetime
  time_field: time
  timestamp_field: timestamp
  json_field: json
  jsonb_field: json
  enu_field: enu
  binary: binary
